export default {
  index: "Home",
  introduction: "Introduction",
  whygimbap: "Why GIMBAP?",
  howitstarted: "How It Started",
  gettingstarted: "Getting Started",
  mainconcepts: "Core Concepts",
  architecture: "Architecture",
  guides: "Practical Guides",
  advanced: "Advanced Topics",
  "api-reference": "API Reference",
  deployment: "Deployment",
  examples: "Examples & Recipes",
  migration: "Migration",
  techniques: "Techniques",
  sampleprojects: "Sample Projects",
  walkthrough: "Walkthrough (WIP)",
};
